# Generated by Django 5.0.7 on 2024-07-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('student_crm', '0002_adminuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminUser',
            new_name='Admin',
        ),
    ]
