# Generated by Django 5.0.7 on 2024-07-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_crm', '0003_rename_adminuser_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(),
        ),
    ]
